### PR TITLE
fixed location

### PR DESCRIPTION
**Pull request by lipovsek-aws**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by sean-smith** [comment]
@lipovsek-aws is this still valid?

**Comment by lipovsek-aws** [comment]
it was when I requested to be reviewed and merged, haven't used it since.

**Comment by lipovsek-aws** [comment]
tested with pcluster 3.6 and P4 ✔️

**Comment by sean-smith** [comment]
Thanks. I've been using it and it works well

**Pull request merged**
